### ISSUE TITLE
一部の動画のコメントが生成されない

### ISSUE THREAD

**Issue by ghost** [jsaori/koyokoyotube#14]
実況スレ登録・コメント反映が行われず、数日以上経過しても登録待ちのままになっている動画があります。  

<img width="504" alt="スクリーンショット 2023-04-19" src="https://user-images.githubusercontent.com/130270825/233062933-d97dc291-99ea-4e07-9437-99091e886d9f.png">

**Comment by jsaori** [comment]
5chにアクセス不可であった期間にGithub Actionsにてコメント生成処理がタイムアウトまで空回り続けた結果、Github Actionsの実行時間無料枠を使いきりその後のコメント生成処理が行われておりませんでした。
5月になれば復旧しますが、それまではローカルPCにてコメント生成処理を実施することで対応します。
4/28(土) 17:43時点にて全コメント反映は完了しております。
